# Generated by Django 3.0.6 on 2020-05-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssociateBill',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill1', models.CharField(max_length=100)),
                ('bill2', models.CharField(max_length=200)),
            ],
        ),
    ]
